---
name: Build & Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.container[1] }}
        if: steps.check.outcome == 'failure'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: steps.check.outcome == 'failure'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements-dev.txt
          make install

      - name: Run Unit tests
        if: steps.check.outcome == 'failure'
        run: |
          . venv/bin/activate
          make test
